### ISSUE TITLE
wtf?

### ISSUE THREAD

**Issue by krinistof** [CsanySoft/TheMosquitoGame#10]
https://github.com/CsanySoft/TheMosquitoGame/blob/a36d009e7be52262823fc27120486cf0a32f5086/core/src/hu/csanysoft/mosquitogame/LoadingScreen.java#L66

**Comment by Majzer** [comment]
Megcsinálom ma délután

**Comment by mrclsu** [comment]
Szerintem legyen 3840.

**Comment by davimatyi** [comment]
nyóc ká alatt nem beszélünk

**Comment by mrclsu** [comment]
szerintem akkor már menjünk egészén húszon négykájig

**Comment by krinistof** [comment]
legyen inkább ká ká
az úgy is van zegen meg a hofi is abba lakik

**Comment by mrclsu** [comment]
@krinistof Így jó lesz? 
```java
width = 'k' + 'á' + 'k' + 'á';
```

**Comment by ErAn156** [comment]
Hé hé akkor már csak igényesen, KáKáKá legyen
