### ISSUE TITLE
Textúrák

### ISSUE THREAD

**Issue by Majzer** [CsanySoft/TheMosquitoGame#2]
Kellenek jó textúrák az Actoroknak, meg egy háttér se ártana

**Comment by krinistof** [comment]
Vízes part mint háttér, az okot adna a szúnyogra?
Erre fel lehetne húzni hogy a két actor üdülő, meg mondjuk volnának a háttérben sátrak
Vélemény?

**Comment by Majzer** [comment]
>           Vízes part mint háttér, az okot adna a szúnyogra?
> Erre fel lehetne húzni hogy a két actor üdülő, meg mondjuk volnának a háttérben sátrak
> Vélemény?

@krinistof  Teljesen jó

**Comment by ErAn156** [comment]
@Majzer what kind of texturák? Semmi infot nem tudok,hogy mire gondoltál desing téren

**Comment by Majzer** [comment]
@ErAn156 Kell egy sétáló ember kinyújtott kézzel, kell valami tengrpartos háttér menübe (@krinistof ) csinált hasonlót, játékhoz kell háttér

**Comment by ErAn156** [comment]
Alpha hátttér megvan
