### ISSUE TITLE
Extrák

### ISSUE THREAD

**Issue by Majzer** [CsanySoft/TheMosquitoGame#5]
Easter Eggek, hasonlók

**Comment by krinistof** [comment]
Majd lesz pár bug, majd azt mondjuk rá, hogy easter egg

**Comment by ErAn156** [comment]
Ha szélnek 42 ad be a user akkor minden azzonal repüljön el a fenébe

**Comment by mrclsu** [comment]
Ha 666-ot akkor még legyenek az emberek véresek és a szúnyog legyen rohadt nagy
